# baseURL = 'http://y0shi.github.io/CRi3H'
baseURL = 'http://www.CRi3H.com'
languageCode = 'en-us'
title = 'CRi3H'

theme = "hugo-book"


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
